---
title: 'Module outline'
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, '00-outline.html'))})
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This course aims to teach some of the key concepts to help learners use R as a tool to inform data-driven decision-making for epidemiological analysis.

Many of the examples in this course are from the [Epidemiologist R handbook](https://epirhandbook.com/index.html), a resource developed by epidemiologists working across the world. The handbook is in invaluable resource for all levels of R users but the focus for this course will be on the early learning concepts most frequently used by epidemiologists. The mapping content has been provided by the [afrimapr](https://afrimapr.github.io/afrimapr.website/) project.

The course has been designed in collaboration with colleagues at Africa CDC to ensure the
topics covered could be implemented in the participants daily/weekly workflows. The data used during this course is from [HERA](https://hera-ngo.org/) and includes confirmed cases notifications for COVID-19 from 53 countries in Africa.
